### ISSUE TITLE
Can’t load the dashboard and can’t even edit my json 

### ISSUE THREAD

**Issue by WOD-MN** [Serial-Studio/Serial-Studio#127]
## Describe the bug
![3CCE3315-F5AB-48C8-B439-A5A2C3EBCF79](https://user-images.githubusercontent.com/70017194/190403651-27c16a1c-b741-48a5-8824-a74d15ba0ff2.jpeg)

![7E89B7D6-BEB3-46FC-98EE-DC2B6BAB46DF](https://user-images.githubusercontent.com/70017194/190403704-96943ecc-0e99-49d4-a721-80708b37c1bb.jpeg)

even i have used examples , i couldn’t load the dashboard!!!
Please help

**Comment by yukelab** [comment]
maybe, you an see issues 101 https://github.com/Serial-Studio/Serial-Studio/issues/101

**Comment by WOD-MN** [comment]
ok

**Comment by alex-spataru** [comment]
@WOD-MN Sorry for closing the issue without responding. The project has changed a lot since this issue was opened and it did not make sense to add an outdated answer in the discussion. Please check the renewed [wiki](https://github.com/Serial-Studio/Serial-Studio/wiki) for guidance on how to setup a project.
