### ISSUE TITLE
Support HEX data frame

### ISSUE THREAD

**Issue by Yurisu** [Serial-Studio/Serial-Studio#134]
1. Support HEX frame start sequence and frame end sequence
2. Customization end line break.(use HEX)
4. Separated by sequence in HEX.
5. Support data show in single byte , double byte , Quad bytes....
6. Customization new queue timer.(use low baud rate , like 4800 / 2400)

**Comment by evalor** [comment]
This is great. I have a frame format, for example: 0xFA7F000085

1. Frame always starts with 0xFA
2. Fixed length, 5 bytes
3. The last byte is XOR verification except for itself.

It would be great if serial studio could work for me.

**Comment by alex-spataru** [comment]
Hi! You might want to try the latest [continuous build](https://github.com/Serial-Studio/Serial-Studio/releases/tag/continuous) in order to parse hex data.

This build allows users to input custom frame-parsing code for project-specific needs. You can modify the frame parser code by clicking on the "Customize frame parser" button in the Project Editor:

<img width="1180" alt="Screenshot 2023-01-22 at 5 30 55" src="https://user-images.githubusercontent.com/4225542/213913612-dc82abf4-9152-442f-9827-64af516164c1.png">

Afterward, you will be presented with a JavaScript code editor:

<img width="752" alt="Screenshot 2023-01-22 at 5 33 10" src="https://user-images.githubusercontent.com/4225542/213913696-75cb85cc-2898-4faf-85cd-e4fd3339a369.png">

**NOTE:** start/end sequences must be strings constructed with ASCII characters. I will update the code to support inputting HEX data/numbers during the course of the week.

Thanks for the idea!

**Comment by mfvmx** [comment]
We have the same thing (hex) but with a variable length, where the second value is length to indicate how many tempurature values will be incoming.

**Comment by alex-spataru** [comment]
> Hello, this feature already enable in latest build? if yes, how can I use it?

Hello! With the [latest release](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v3.0.0), it’s now possible to work with Hexadecimal data in Serial Studio. You can find an example [here](https://github.com/Serial-Studio/Serial-Studio/tree/master/examples/HexadecimalADC). I’ll close this issue for now, but feel free to let me know if it should be re-opened.
