### ISSUE TITLE
无法正常使用仪表盘和小部件

### ISSUE THREAD

**Issue by tarler** [Serial-Studio/Serial-Studio#230]
**Bug Report Template**

---

### **1. Describe the bug**

> Provide a clear and concise description of the bug you’re experiencing.  

[Your answer here]

### **2. Screenshots (if applicable)**

> Add screenshots to help illustrate the problem, if applicable.  

[Attach your screenshots here]

### **3. Upload your JSON map file**

> This is essential for reproducing any UI-related issues.  

[Attach your JSON map file here]

### **4. Provide a minimal Arduino program to replicate the issue**

> Sharing a minimal Arduino sketch helps me replicate the environment and setup that causes the bug.  

[Your Arduino sketch here]  

Here’s an example of a minimal program:  

```cpp
void setup() {
    Serial.begin(115200);
    while (!Serial);
}

void loop() {
    Serial.println("/*1,2,3*/");
    delay(50);
}
```

### **4. Important Notes**

- Non-critical bugs will be treated with **lower priority than critical bugs**.  
- Donations are always welcome to help keep the project alive and ensure a timely response. You can support the project here: [Donate Now](https://www.paypal.com/donate?hosted_button_id=XN68J47QJKYDE).  
- **I am an open-source developer.** I provide this software as-is and cannot be responsible for long-term maintenance or personalized service. The source code is available freely, and if the issue is urgent, you’re encouraged to fix it yourself or hire someone (including myself) to do so.  

Thank you for understanding and for helping improve the software!

---

### **1. 描述问题**

> 请清晰简洁地描述您遇到的问题。  

[请在这里填写您的答案]
小部件和仪表盘成灰色无法正常使用
### **2. 截图（如果适用）**
![QQ20241121-180209](https://github.com/user-attachments/assets/c900d250-909a-473b-a5dc-21acf2a5ec80)

> 如果适用，请添加截图以帮助说明您的问题。  

[在此处附加您的截图]

### **3. 上传您的 JSON 地图文件**

> 这是重现任何与 UI 相关问题的必要条件。  

[在此处附加您的 JSON 地图文件]

### **4. 提供一个最小的 Arduino 程序以复现问题**

> 提供一个最小的 Arduino 程序有助于我复现导致问题的环境和设置。  

[请在此填写您的 Arduino 程序]  

程序的基本步骤包括：

```cpp
void setup() {
    Serial.begin(115200);
    while (!Serial);
}

void loop() {
    Serial.println("/*1,2,3*/");
    delay(50);
}
```

### **5. 注意事项**

- **非关键性问题的优先级将低于关键性问题。**  
- 欢迎通过[捐赠链接](https://www.paypal.com/donate?hosted_button_id=XN68J47QJKYDE)支持该项目，以帮助项目持续开发并确保及时响应。  
- **我是一个开源开发者。** 我提供此软件是“按原样”的，我无法负责长期维护或个性化服务。源代码是免费提供的，如果问题很紧急，建议您自己修复或雇佣他人（包括我）进行修复。  

感谢您的理解并帮助改进此软件！

**Comment by alex-spataru** [comment]
Hi! For detailed information on configuring a project file, the various operation modes, and more, please refer to the [wiki](https://github.com/Serial-Studio/Serial-Studio/wiki/). To get started quickly, check out the [Getting Started Guide](https://github.com/Serial-Studio/Serial-Studio/wiki/Getting-Started#connecting-a-device-quick-plot-mode), which provides a simple example to help you get up and running. From there, you can gradually explore and work on more advanced projects.

I’ll go ahead and close this issue since the wiki covers most of these details. Please note that the wiki is written in English (even though it’s not my native language) to make it accessible to a broader audience. If needed, feel free to use translation services to help with understanding. Let me know if you have further questions!

---

有关配置项目文件、不同操作模式等详细信息，请参阅 [wiki](https://github.com/Serial-Studio/Serial-Studio/wiki/)。如果您想快速上手，请查看 [Getting Started Guide](https://github.com/Serial-Studio/Serial-Studio/wiki/Getting-Started#connecting-a-device-quick-plot-mode)，其中提供了一个简单的示例，帮助您快速入门。从那里，您可以逐步探索并开展更高级的项目。

我将关闭此问题，因为 wiki 已经涵盖了大部分相关细节。请注意，wiki 是用英语编写的（尽管这并不是我的母语），以便为更广泛的用户提供帮助。如果需要，您可以使用翻译服务来帮助理解。如果还有其他问题，请随时告诉我！
