### ISSUE TITLE
Cannot set 3000000 baud

### ISSUE THREAD

**Issue by willtoth** [Serial-Studio/Serial-Studio#27]
**Describe the bug**
When I manually type in 3000000 for the baud rate, the output is not correct. I can confirm in other terminal programs that the data is received correctly.

![image](https://user-images.githubusercontent.com/8404869/107266907-ca879600-6a0b-11eb-9187-afb162745781.png)

**Comment by alex-spataru** [comment]
Hi, could you please send me your application log to check if the serial port module reports an error? You can find the application logs in `About` ➝ `Open log file`:

![Screen Shot 2021-02-08 at 17 55 11](https://user-images.githubusercontent.com/4225542/107292039-261b4900-6a37-11eb-8bdd-0cc465ce2cb5.png)

Thanks for the report!

**Comment by alex-spataru** [comment]
In my case, I cannot set to 3000000 baud because the MCUs that I have do not support such speeds. Here is a screenshot of the output in CoolTerm:

![Screen Shot 2021-02-10 at 0 25 31](https://user-images.githubusercontent.com/4225542/107468819-b55b5600-6b36-11eb-991e-5c332e12d339.png)

And a `qDebug` printout of the data received directly from the serial port (before its added to the UI console display):

![Screen Shot 2021-02-10 at 0 25 42](https://user-images.githubusercontent.com/4225542/107468913-d2902480-6b36-11eb-83de-4d955ef4a230.png)

And regarding the overlapped characters in your screenshot, this is currently being fixed. In SS 1.0.14 and 1.0.15 I tried to implement my own text editor widget because the QML text editor offered by Qt was too slow for logging.

However, I am now using a QPlainTextEditor and integrating it to the QML interface, which solves the performance issue and avoids these kinds of UI glitches.
