### ISSUE TITLE
syntax issues

### ISSUE THREAD

**Issue by senliontec** [Serial-Studio/Serial-Studio#61]
In Console.cpp

Line 283:  QFileDialog::getSaveFileName(Q_NULLPTR, tr("Export console data"),
                                       QDir::homePath(), tr("Text files") + " (*.txt)");

it might be: QFileDialog::getSaveFileName(Q_NULLPTR, tr("Export console data"),
                                       QDir::homePath(), tr("Text files") + tr(" (*.txt)"));

**Comment by alex-spataru** [comment]
Hi, removing the `tr("*.txt")` part is intended in this scenario because we want to avoid issues when the translation has a different character for `*` and `.`. If the translation defines a different character, then the user will not be able to save any text files. You can check this [commit](https://github.com/Serial-Studio/Serial-Studio/commit/a5fa084fd5db02cc142b225fa5d2a22abe09c6b2) for more info.

Anyways, thanks for the interest & the previous bug/issue reports!
